name: test
on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out this project
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - run: npm ci
      - name: "Make example site"
        run: |
          mkdir site
          tee site/example.html << 'END'
          <!DOCTYPE html>
          <html lang="en">
            <head><title>Test Page</title></head>
            <body>
              <h1>Hello World</h1>
              Vanilla ice cream is the best ice cream.
            </body>
          </html>
          END
      - name: "Launch http server"
        run: |
          npm i -g http-server
          http-server site &
          until nc -z localhost 8080 2>/dev/null; do
            echo 'Waiting for http server'
            sleep 1
          done
      - name: Take snapshot
        run: |
          node snap-site.js \
          --site-dir=./site \
          --out-dir=test-output  \
          --host-port=localhost:8080
      - name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: test-output
